### ISSUE TITLE
Too many bugs in mono_following_node.py?

### ISSUE THREAD

**Issue by youzunzhi** [MedlarTea/Mono-RPF#10]
Thank you for your great work! It seems there is something wrong with mono_following_code.py because there are too many basic bugs in this file, such as undefined `self.params`, mismatched initialization of `PartTracklet` (line 92), `self.identifier` should be `self.descriminator`, etc. I was wondering if you could update this file to a working version. Everything else looks great.

**Comment by MedlarTea** [comment]
I'm sorry for not getting back to you sooner, it's too busy these days! Oh, we might update the wrong version of the mono_following_node.py; I will check it tomorrow and update the correct version. Once I upload it, I will inform you.

**Comment by MedlarTea** [comment]
I just uploaded the correct version of mono_following_code.py. Thanks for your interest in our work.
