### ISSUE TITLE
spencer_tracking_msgs files missing (Box.h and TargetPerson.h)

### ISSUE THREAD

**Issue by pipperv** [MedlarTea/Mono-RPF#2]
Hi! I'm trying to use the code, but when trying to build on a catkin ws there is two msgs files missing,  <spencer_tracking_msgs/Box.h> and <spencer_tracking_msgs/TargetPerson.h>, I already installed 'spencer_tracking_msgs' from 'https://github.com/spencer-project/spencer_messages' but there is no 'Box.h' or 'TargetPErson.h'. Am I missing something? is there a place where I can find those files?

Thanks! Great work by the way :3

**Comment by MedlarTea** [comment]
Thanks for noticing that. I just uploaded all related message files, you can catkin_make again. It should work now.
