### ISSUE TITLE
Acess Deny of Yolox Weights

### ISSUE THREAD

**Issue by Mandan-CHAO** [MedlarTea/Mono-RPF#3]
Hi, thanks for your code sharing! I found that when I tried to download pre-trained weights for part _1) Download bounding-box detection models: yolox-s and yolox-m_, it showcased the page with a warning of AccessDenied. I wonder if anywhere I could find these weights\ files.

**Comment by Mandan-CHAO** [comment]
Is it the same model from https://github.com/Megvii-BaseDetection/YOLOX/tree/main? yolox-s and yolox-m?

**Comment by MedlarTea** [comment]
I just uploaded the weights to Google Drive: https://drive.google.com/drive/folders/1a-z4zPpZX6XVwtklhTybydMcgH9JqZKR?usp=drive_link. Try these.
