### ISSUE TITLE
Implementation this code on own video.

### ISSUE THREAD

**Issue by Bajrangi97** [MedlarTea/Mono-RPF#4]
Hi, thank you for your excellent work, How to implement this code on my own dataset.

**Comment by MedlarTea** [comment]
One possible way is to extract images from your own video, and then make a rosbag from the images.

**Comment by Bajrangi97** [comment]
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_workspace.cmake:121 (add_subdirectory):
  The source directory

    /mnt/DATA/EE22M204/catkin_ws-org/src/mono-rpf-main

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)

I am getting this error , but CMakeLists.txt is there inside the mono-rpf-main. is this any issue in package?? 
How to fixed it??

Refference  path of CMakeLists.txt.
/mnt/DATA/EE22M204/catkin_ws-org/src/mono-rpf-main/CMakeLists.txt

**Comment by Bajrangi97** [comment]
how to fix this issue?
make[2]: *** Deleting file '/mnt/DATA/EE22M204/catkin_wss/devel/include/mono_following/extractDescriptors.h'
make[2]: *** [Mono-rpf/mono_following/CMakeFiles/mono_following_generate_messages_cpp.dir/build.make:184: /mnt/DATA/EE22M204/catkin_wss/devel/include/mono_following/updateDescriptors.h] Error 1
make[2]: *** Deleting file '/mnt/DATA/EE22M204/catkin_wss/devel/include/mono_following/updateDescriptors.h'
make[1]: *** [CMakeFiles/Makefile2:7105: Mono-rpf/mono_following/CMakeFiles/mono_following_generate_messages_cpp.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j40 -l40" failed

**Comment by Bajrangi97** [comment]
Thanks
