### ISSUE TITLE
Multiple packages found with the same name

### ISSUE THREAD

**Issue by Bajrangi97** [MedlarTea/Mono-RPF#5]
Thanks for sharing your work. In this repository folder structure is like as  
In the main folder there is a folder with name visualization and inside the message folder again there is a visualization folder, due to this while building the catkin I am getting this warning and unable to build catkin. I am attaching the snapshot

"""

(mono_following) ee22m204@iit7-Z10PE-D8-WS:~/catkin_wss$ catkin_make
Base path: /mnt/DATA/EE22M204/catkin_wss
Source space: /mnt/DATA/EE22M204/catkin_wss/src
Build space: /mnt/DATA/EE22M204/catkin_wss/build
Devel space: /mnt/DATA/EE22M204/catkin_wss/devel
Install space: /mnt/DATA/EE22M204/catkin_wss/install
Multiple packages found with the same name "spencer_tracking_rviz_plugin":
- Mono-rpf/messages/visualization/spencer_tracking_rviz_plugin
- Mono-rpf/visualization/spencer_tracking_rviz_plugin
Multiple packages found with the same name "srl_tracking_exporter":
- Mono-rpf/messages/visualization/srl_tracking_exporter
- Mono-rpf/visualization/srl_tracking_exporter
(mono_following) ee22m204@iit7-Z10PE-D8-WS:~/catkin_wss$ 

"""
how can I manage this?

**Comment by MedlarTea** [comment]
Sorry for this mistake. Just delete the "visualization" folder which contains repetitive messages for visualization. I uploaded a new version of the code that does not contain the "visualization" folder.

**Comment by Bajrangi97** [comment]
Thanks for update.

**Comment by Bajrangi97** [comment]
Thanks for your response.
Can you please provide your dataset. That will be very helpful for me.

Thanks & Regards

Bajrangi sahni
***@***.***
