### ISSUE TITLE
multiple packages with same name

### ISSUE THREAD

**Issue by VijayRajIITP** [MedlarTea/Mono-RPF#6]
Thanks for sharing your valuable research. I am very impress by your work.
I want to implement this code in my system.
I have one question about this repository. Is this repository is completely uploaded?
There are two visualisation folder in this repository so while building the catkin I am getting the warning " multiple packages with same name", I had tried to building the catkin after removing one of the visualisation folder exist inside the message , then I am getting error. 
can you suggest me better way to fixed this issues?

**Comment by MedlarTea** [comment]
Sorry for this mistake. Just delete the "visualization" folder which contains repetitive messages for visualization. I uploaded a new version of the code that does not contain the "visualization" folder.
