### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by jambalaya666** [MedlarTea/Mono-RPF#7]
Thank you for your excellent work. Can you share the dataset set you used?

**Comment by MedlarTea** [comment]
You can download them from here: https://drive.google.com/drive/folders/1M-H4Y2WA5zNn9-LnSy6RL25OTnucDGzc?usp=sharing

**Comment by jambalaya666** [comment]
你好，你发的信件我已收到，谢谢！

**Comment by jambalaya666** [comment]
Hello, I saw the topic data of lidar_topic = "/velodyne_points" from your code. I would like to ask you what is the main use of lidar data. Can you provide a rosbag file containing lidar data that you use?

**Comment by Champrin** [comment]
> 你好，你发的信件我已收到，谢谢！

你好打扰了，请问还留有作者提供的数据集吗，上面的链接里数据似乎被删除了

**Comment by jambalaya666** [comment]
您发的信件我已收到，谢谢！
