### ISSUE TITLE
请求指导：使用OCL和摄像头进行人体识别的实现方法

### ISSUE THREAD

**Issue by proxi666** [MedlarTea/Mono-RPF#9]
尊敬的作者们，
您好！我对您们的工作非常感兴趣并深表钦佩。我是一名本科生，目前正在进行一个关于计算机视觉的项目。我已经详细阅读并理解了您们的研究论文，但在阅读代码时遇到了一些困难。
我希望能够学习您们使用OCL和摄像头来识别人的方法，并在项目中实现这一点。能否请您们帮忙指导一下？根据我过去5-6天的理解，我需要使用 mono_tracker、mono_following 和 messages 包。我的思路是否正确？
提前感谢您们的帮助！ :)

**Comment by MedlarTea** [comment]
你好，OCL部分的代码我们正在整理，将会在近期开源。

**Comment by proxi666** [comment]
谢谢您的回复，所以代码还没有完全开发完成，对吗？不过，我还是可以使用您目前已开发的部分代码吗？也就是我认为的ReID + byteTracker部分。

**Comment by MedlarTea** [comment]
已经开发完成，但我们作者觉得可以简化后再开源，方便大家使用，所以会稍晚些公布（预计12月初），其中代码包括了byteTracker+ReID部分。当前的Mono-RPF也有ReID的功能，您可以先行尝试。谢谢您对我们工作的关注！

**Comment by proxi666** [comment]
非常感谢您的回复，我会先着手研究当前的代码，并会在十二月时关注新版本的发布 :)

**Comment by proxi666** [comment]
你好，我正在尝试在我的系统上复现你的工作，但遇到了 mmcv 的问题。你提到它是“修改过的 mmtrack”，能否请你提供一个合适的版本？另外，我只是想让你的工作在我的摄像头上运行，你能给我一些实现的建议吗？提前感谢！

**Comment by MedlarTea** [comment]
这部分代码将稍晚些公布（预计12月初）
